import { Versionhistory } from "./versionhistory.model";

export class Imd{
    constructor(
        public imdcode:number,
        public imdname:string,
        public entrydate:number,
        public accountmanager:number,
        public comcha:number,
        public verticalcode:string,
        public buisnessvertical:string,
        public imdchannel:string,
        public irda:string,
        public salesunit:string,
        public salescenter:string,
        public salesarea:string,
        public directorate:string,
        public division:string,
        public locationcode:number,
        public city:string,
        public pincode:number,
        public pickupcode:number,
        public pickupcity:string,
        public staffid:number,
        public pcid:string,
        public floatac:string,
        public webid:string,
        public deactivatedate:Date,
        public accstatus:string,
        public block_reason:string,
        public team:string,
        public zone:string,
        public codests:string,
        public amcode:number,
        public amname:string,
        public channel:string,
        public pricingchannel:number,
        public rmcode:number,
        public rmname:string,
        public vhcode:number,
        public vhname:string,
        public lhcode:number,
        public lhname:string,
        public rhcode:number,
        public rhname:string,
        public zhcode:number,
        public zhname:string,
        public from:Date,
        public to:Date,
        public versionhistory:Array<Versionhistory>
    ){}
}