import { Component, OnInit, ViewChild } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { MatPaginator } from '@angular/material/paginator';
import { ChangeamComponent } from 'src/app/common/changeam/changeam.component';
import { BulkuploadComponent } from '../../employee/partials/bulkupload/bulkupload.component';
import { EditemployeeformComponent } from '../../employee/partials/editemployeeform/editemployeeform.component';
import { VersionhistoryComponent } from '../../employee/partials/versionhistory/versionhistory.component';
import { EditimdformComponent } from '../partials/editimdform/editimdform.component';

@Component({
  selector: 'app-imddetails',
  templateUrl: './imddetails.component.html',
  styleUrls: ['./imddetails.component.css']
})
export class ImddetailsComponent implements OnInit {
  imds=[
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },

    {
      imdcode:"1000010",
      imdname:"Digit Direct",
      entrydate:"43034",
      accountmanager:"1000157",
      comcha:"126",
      verticalcode:"DI",
      buisnessvertical:"DI",
      imdchannel:"Direct Sale",
      irda:"DESL-Direct Sale",
      salesunit:"Sales Unit Direct",
      salescenter:"Sales Center Direct",
      salesarea:"Anuj Jain",
      directorate:"Strategic Patnership",
      division:"Bengaluru-Retail Buisness",
      locationcode:"12901",
      city:"Bangalore South",
      pincode:560034,
      pickupcode:232323,
      pickupcity:"Bengaluru",
      staffid:910005,
      pcid:"U0005",
      floatac:"U0005",
      webid:"89585040 Y,88709868 Y,69596723",
      deactivatedate:"12-1-21",
      accstatus:"Active",
      block_reason:"N/A",
      team:"Institutional South",
      zone:"Institutional",
      codests:"Active",
      amcode:1000010,
      amname:"Digit Direct",
      channel:"Institutional",
      pricingchannel:126,
      rmcode:126,
      rmname:"Krithiga Magothra",
      vhcode:342,
      vhname:"sujith",
      lhcode:876,
      lhname:"john doe",
      rhcode:231,
      rhname:"vijay sekhar",
      zhcode:456,
      zhname:"Rahul sharma",
      from:"3-4-2020",
      to:"5-7-2020",
      versionhistory:[
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
        {
          details:"Employee channel changed from Broker to Agency",
          datetime:"31st Dec 2020 at 5:15pm",
          modifiedby:"john doe"
        },
      ]
    },
  ]
  @ViewChild(MatPaginator) paginator: MatPaginator;

  constructor(public dialog: MatDialog) {}

  ngOnInit(): void {
  }
  openbulkupload(){
    const dialogRef = this.dialog.open(BulkuploadComponent);
  }
  openeditimd(){
    const dialogRef = this.dialog.open(EditimdformComponent);
  }
  openversionhistory(data){
    const dialogRef = this.dialog.open(VersionhistoryComponent,{
      data:data
    })
  }
  openchangeam(){
    const dialogRef = this.dialog.open(ChangeamComponent)
  }
}
