const target=[
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
    {
        empname:"john",
        empcode:12345,
        role:"Buisness Head",
        zone:"North-1",
        locations:["Bangalore","Gurgaon"],
        locationhead:"Chandra sekhar sharma",
        channel:["Retail","Insurance","Motor"],
        channelheadname:"sujith",
        lob:"Marketing",
        model:"Go-digit",
        rmname:"john doe",
        rmcode:165432,
        imdcode:87980,
        imdname:"shiva sankar",
        nb:12654,
        rollover:6500,
        renewal:15000,
        ltp:90900,
        talloc:98000,
        totass:100000,
    },
]


export default target;